SUPABASE_URL = "https://lbkcusdohljcuaxvskzb.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxia2N1c2RvaGxqY3VheHZza3piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1ODE5NTgsImV4cCI6MjA1NDE1Nzk1OH0.xldl_xqy9xC-cMoAhkvalVYRuazJ5NTJ-XPQCRaodfE"
